Compile error due to wrong include
$ make
[  8%] Building CXX object src/CMakeFiles/kallisto_core.dir/main.cpp.o
In file included from /usr/local/src/kallisto-0.42/src/Bootstrap.h:7:0,
                 from /usr/local/src/kallisto-0.42/src/main.cpp:27:
/usr/local/src/kallisto-0.42/src/Multinomial.hpp: In member function ‘std::vector<int> Multinomial::sample(int)’:
/usr/local/src/kallisto-0.42/src/Multinomial.hpp:35:23: error: ‘domain_error’ is not a member of ‘std’


Changing the include to stdexcept fixed it. 

(see http://stackoverflow.com/questions/25163105/stdexcept-vs-exception-headers-in-c)